image: wondermonger/ci-tools:v2

stages:
  - install
  - lint
  - deploy

install:
  artifacts:
    paths:
      - node_modules/
  script: ci-node-install
  stage: install

outdated:
  allow_failure: true
  script: ci-node-outdated
  stage: install

lint:
  script: ci-node-lint
  stage: lint

release:
  only:
    - master
  script:
    - ci-git-config
    - ci-git-release
  stage: deploy

publish:
  only:
    - tags
  script:
    - ci-node-config
    - ci-node-release
  stage: deploy
